package scid3.model.frames

object FrameBodyType extends Enumeration {
	val ASPI = Value
	val APIC = Value
	val APICID3V22 = Value
	val COMM = Value
	val COMR = Value
	val CRM = Value
	val ENCR = Value
	val GEOB = Value
	val GRID = Value
	val RVRB = Value
	val LINK = Value
	val MCDI = Value
	val PCNT = Value
	val POPM = Value
	val PRIV = Value
	//val RVAD = Value
	val RBUF = Value
	val SYLT = Value
	val TALB = Value
	val ETCO = Value
	val TBPM = Value
	val TCOM = Value
	val TCON = Value
	val TCOP = Value
	val TDAT = Value // Deprecated
	val TDEN = Value
	val TDLY = Value
	val TDOR = Value
	val TDRC = Value
	val PIC = Value
	val POSS = Value
	val TDRL = Value
	val TDTG = Value
	val OWNE = Value
	val TENC = Value
	val SEEK = Value
	val TEXT = Value
	val TFLT = Value
	val TIME = Value // Deprecated
	val TIPL = Value
	val TIT1 = Value
	val TIT2 = Value
	val TIT3 = Value
	val TKEY = Value
	val TLAN = Value
	val TLEN = Value
	val TMCL = Value
	val TMED = Value
	val TMOO = Value
	val TOAL = Value
	val TOFN = Value
	val TOLY = Value
	val TOPE = Value
	val TORY = Value // Deprecated
	val TOWN = Value
	val TPE1 = Value
	val TPE2 = Value
	val TPE3 = Value
	val TPE4 = Value
	val TPOS = Value
	val TPRO = Value
	val TPUB = Value
	val TRCK = Value
	val TRDA = Value // Deprecated
	val TRSN = Value
	val TRSO = Value
	val TSIZ = Value // Deprecated
	val TSOA = Value
	val SIGN = Value
	val TSOP = Value
	val TSOT = Value
	val TSRC = Value
	val TSSE = Value
	val TSST = Value
	val TXXX = Value
	val TYER = Value // Deprecated
	val UFID = Value
	val USER = Value
	val USLT = Value
	val WCOM = Value
	val WCOP = Value
	val WOAF = Value
	val WOAR = Value
	val WOAS = Value
	val WORS = Value
	val WPAY = Value
	val WPUB = Value
	val WXXX = Value

	// extended

	val AENC = Value
	val UNSUPPORTED = Value
}